server:
  port: 8080

spring:
  application:
    name: ones-admin-server

sa-token:
  token-name: Authorization
  token-prefix: Bearer
  timeout: 86400
  active-timeout: -1
  is-concurrent: true
  is-share: false
  is-read-header: true
  is-read-body: false
  is-read-cookie: false
  is-print: false

management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  swagger-ui:
    path: /swagger-ui.html
