server:
  port: 8080

spring:
  application:
    name: ones-admin-server
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:ones-admin;MODE=MySQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1
    username: sa
    password:
  sql:
    init:
      mode: always

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

sa-token:
  token-name: Authorization
  token-prefix: Bearer
  timeout: 86400
  active-timeout: -1
  is-concurrent: true
  is-share: false
  is-read-header: true
  is-read-body: false
  is-read-cookie: false
  is-print: false

management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  swagger-ui:
    path: /swagger-ui.html
