create table if not exists sys_user (
    id bigint generated by default as identity primary key,
    username varchar(64) not null,
    display_name varchar(64) not null,
    avatar varchar(512),
    password_hash varchar(128) not null,
    enabled boolean not null default true,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint uk_sys_user_username unique (username)
);

create table if not exists sys_role (
    id bigint generated by default as identity primary key,
    code varchar(64) not null,
    name varchar(64) not null,
    enabled boolean not null default true,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint uk_sys_role_code unique (code)
);

create table if not exists sys_permission (
    id bigint generated by default as identity primary key,
    code varchar(128) not null,
    name varchar(128) not null,
    created_at timestamp not null default current_timestamp,
    constraint uk_sys_permission_code unique (code)
);

create table if not exists sys_user_role (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    role_id bigint not null,
    created_at timestamp not null default current_timestamp,
    constraint uk_sys_user_role unique (user_id, role_id)
);

create table if not exists sys_role_permission (
    id bigint generated by default as identity primary key,
    role_id bigint not null,
    permission_id bigint not null,
    created_at timestamp not null default current_timestamp,
    constraint uk_sys_role_permission unique (role_id, permission_id)
);
